### ISSUE TITLE
Ensure operator is RH certified

### ISSUE THREAD

**Issue by horis233** [IBM/operand-deployment-lifecycle-manager#44]
- [x] operator-sdk scorecard #45 
- [x] operator-courier verify #46 
- [ ] RedHat certified operator on boarding #47 
- [ ] IBM certification #48 
https://playbook.cloudpaklab.ibm.com/operator-certification
